version: "3.7"

services:
  mongo:
    image: mongo
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: fbscrapper
      MONGO_NON_ROOT_USERNAME: admin
      MONGO_NON_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - fbscrapper_mongo_data:/data/db
      - ./configs/docker/mongodb/custom-user.sh:/docker-entrypoint-initdb.d/custom-user.sh

  mongo-express:
    image: mongo-express
    restart: "no"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    depends_on:
      - mongo

  ghost:
    image: koorosh/ghost:latest
    restart: "no"
    ports:
      - 8888:2368
    environment:
      url: http://localhost:8888
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
    depends_on:
      - db

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  fbscrapper_mongo_data:
